// Copyright (c) 2024, zhao.shaowei <nsearchf@yeah.net>
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.

/* Automatically generated by parse_opcodes */
pub(crate) const MATCH_MRET: u32 = 0x30200073;
pub(crate) const MASK_MRET: u32 = 0xffffffff;
pub(crate) const MATCH_WFI: u32 = 0x10500073;
pub(crate) const MASK_WFI: u32 = 0xffffffff;
