// Copyright (c) 2024, zhao.shaowei <nsearchf@yeah.net>
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.

/* Automatically generated by parse_opcodes */
pub(crate) const MATCH_CSRRC: u32 = 0x3073;
pub(crate) const MASK_CSRRC: u32 = 0x707f;
pub(crate) const MATCH_CSRRCI: u32 = 0x7073;
pub(crate) const MASK_CSRRCI: u32 = 0x707f;
pub(crate) const MATCH_CSRRS: u32 = 0x2073;
pub(crate) const MASK_CSRRS: u32 = 0x707f;
pub(crate) const MATCH_CSRRSI: u32 = 0x6073;
pub(crate) const MASK_CSRRSI: u32 = 0x707f;
pub(crate) const MATCH_CSRRW: u32 = 0x1073;
pub(crate) const MASK_CSRRW: u32 = 0x707f;
pub(crate) const MATCH_CSRRWI: u32 = 0x5073;
pub(crate) const MASK_CSRRWI: u32 = 0x707f;
