// Copyright (c) 2024, zhao.shaowei <nsearchf@yeah.net>
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.


/* Automatically generated by parse_opcodes */
const MATCH_DIVUW: u32 = 0x200503b;
const MASK_DIVUW: u32 = 0xfe00707f;
const MATCH_DIVW: u32 = 0x200403b;
const MASK_DIVW: u32 = 0xfe00707f;
const MATCH_MULW: u32 = 0x200003b;
const MASK_MULW: u32 = 0xfe00707f;
const MATCH_REMUW: u32 = 0x200703b;
const MASK_REMUW: u32 = 0xfe00707f;
const MATCH_REMW: u32 = 0x200603b;
const MASK_REMW: u32 = 0xfe00707f;
