// Copyright (c) 2024, zhao.shaowei <nsearchf@yeah.net>
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.


/* Automatically generated by parse_opcodes */
const MATCH_MRET: u32 = 0x30200073;
const MASK_MRET: u32 = 0xffffffff;
const MATCH_WFI: u32 = 0x10500073;
const MASK_WFI: u32 = 0xffffffff;
