// Copyright (c) 2024, zhao.shaowei <nsearchf@yeah.net>
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.


/* Automatically generated by parse_opcodes */
const MATCH_AMOADD_W: u32 = 0x202f;
const MASK_AMOADD_W: u32 = 0xf800707f;
const MATCH_AMOAND_W: u32 = 0x6000202f;
const MASK_AMOAND_W: u32 = 0xf800707f;
const MATCH_AMOMAX_W: u32 = 0xa000202f;
const MASK_AMOMAX_W: u32 = 0xf800707f;
const MATCH_AMOMAXU_W: u32 = 0xe000202f;
const MASK_AMOMAXU_W: u32 = 0xf800707f;
const MATCH_AMOMIN_W: u32 = 0x8000202f;
const MASK_AMOMIN_W: u32 = 0xf800707f;
const MATCH_AMOMINU_W: u32 = 0xc000202f;
const MASK_AMOMINU_W: u32 = 0xf800707f;
const MATCH_AMOOR_W: u32 = 0x4000202f;
const MASK_AMOOR_W: u32 = 0xf800707f;
const MATCH_AMOSWAP_W: u32 = 0x800202f;
const MASK_AMOSWAP_W: u32 = 0xf800707f;
const MATCH_AMOXOR_W: u32 = 0x2000202f;
const MASK_AMOXOR_W: u32 = 0xf800707f;
const MATCH_LR_W: u32 = 0x1000202f;
const MASK_LR_W: u32 = 0xf9f0707f;
const MATCH_SC_W: u32 = 0x1800202f;
const MASK_SC_W: u32 = 0xf800707f;
