// Copyright (c) 2024, zhao.shaowei <nsearchf@yeah.net>
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.


/* Automatically generated by parse_opcodes */
const MATCH_C_JAL: u32 = 0x2001;
const MASK_C_JAL: u32 = 0xe003;
const MATCH_C_SLLI: u32 = 0x2;
const MASK_C_SLLI: u32 = 0xf003;
const MATCH_C_SRAI: u32 = 0x8401;
const MASK_C_SRAI: u32 = 0xfc03;
const MATCH_C_SRLI: u32 = 0x8001;
const MASK_C_SRLI: u32 = 0xfc03;
