// Copyright (c) 2024, zhao.shaowei <nsearchf@yeah.net>
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.


/* Automatically generated by parse_opcodes */
const MATCH_C_ADD: u32 = 0x9002;
const MASK_C_ADD: u32 = 0xf003;
const MATCH_C_ADDI: u32 = 0x1;
const MASK_C_ADDI: u32 = 0xe003;
const MATCH_C_ADDI16SP: u32 = 0x6101;
const MASK_C_ADDI16SP: u32 = 0xef83;
const MATCH_C_ADDI4SPN: u32 = 0x0;
const MASK_C_ADDI4SPN: u32 = 0xe003;
const MATCH_C_AND: u32 = 0x8c61;
const MASK_C_AND: u32 = 0xfc63;
const MATCH_C_ANDI: u32 = 0x8801;
const MASK_C_ANDI: u32 = 0xec03;
const MATCH_C_BEQZ: u32 = 0xc001;
const MASK_C_BEQZ: u32 = 0xe003;
const MATCH_C_BNEZ: u32 = 0xe001;
const MASK_C_BNEZ: u32 = 0xe003;
const MATCH_C_EBREAK: u32 = 0x9002;
const MASK_C_EBREAK: u32 = 0xffff;
const MATCH_C_J: u32 = 0xa001;
const MASK_C_J: u32 = 0xe003;
const MATCH_C_JALR: u32 = 0x9002;
const MASK_C_JALR: u32 = 0xf07f;
const MATCH_C_JR: u32 = 0x8002;
const MASK_C_JR: u32 = 0xf07f;
const MATCH_C_LI: u32 = 0x4001;
const MASK_C_LI: u32 = 0xe003;
const MATCH_C_LUI: u32 = 0x6001;
const MASK_C_LUI: u32 = 0xe003;
const MATCH_C_LW: u32 = 0x4000;
const MASK_C_LW: u32 = 0xe003;
const MATCH_C_LWSP: u32 = 0x4002;
const MASK_C_LWSP: u32 = 0xe003;
const MATCH_C_MV: u32 = 0x8002;
const MASK_C_MV: u32 = 0xf003;
const MATCH_C_NOP: u32 = 0x1;
const MASK_C_NOP: u32 = 0xef83;
const MATCH_C_OR: u32 = 0x8c41;
const MASK_C_OR: u32 = 0xfc63;
const MATCH_C_SUB: u32 = 0x8c01;
const MASK_C_SUB: u32 = 0xfc63;
const MATCH_C_SW: u32 = 0xc000;
const MASK_C_SW: u32 = 0xe003;
const MATCH_C_SWSP: u32 = 0xc002;
const MASK_C_SWSP: u32 = 0xe003;
const MATCH_C_XOR: u32 = 0x8c21;
const MASK_C_XOR: u32 = 0xfc63;
