// Copyright (c) 2024, zhao.shaowei <nsearchf@yeah.net>
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.


/* Automatically generated by parse_opcodes */
const MATCH_FCVT_D_L: u32 = 0xd2200053;
const MASK_FCVT_D_L: u32 = 0xfff0007f;
const MATCH_FCVT_D_LU: u32 = 0xd2300053;
const MASK_FCVT_D_LU: u32 = 0xfff0007f;
const MATCH_FCVT_L_D: u32 = 0xc2200053;
const MASK_FCVT_L_D: u32 = 0xfff0007f;
const MATCH_FCVT_LU_D: u32 = 0xc2300053;
const MASK_FCVT_LU_D: u32 = 0xfff0007f;
const MATCH_FMV_D_X: u32 = 0xf2000053;
const MASK_FMV_D_X: u32 = 0xfff0707f;
const MATCH_FMV_X_D: u32 = 0xe2000053;
const MASK_FMV_X_D: u32 = 0xfff0707f;
