// Copyright (c) 2024, zhao.shaowei <nsearchf@yeah.net>
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.


/* Automatically generated by parse_opcodes */
const MATCH_DIV: u32 = 0x2004033;
const MASK_DIV: u32 = 0xfe00707f;
const MATCH_DIVU: u32 = 0x2005033;
const MASK_DIVU: u32 = 0xfe00707f;
const MATCH_MUL: u32 = 0x2000033;
const MASK_MUL: u32 = 0xfe00707f;
const MATCH_MULH: u32 = 0x2001033;
const MASK_MULH: u32 = 0xfe00707f;
const MATCH_MULHSU: u32 = 0x2002033;
const MASK_MULHSU: u32 = 0xfe00707f;
const MATCH_MULHU: u32 = 0x2003033;
const MASK_MULHU: u32 = 0xfe00707f;
const MATCH_REM: u32 = 0x2006033;
const MASK_REM: u32 = 0xfe00707f;
const MATCH_REMU: u32 = 0x2007033;
const MASK_REMU: u32 = 0xfe00707f;
