// Copyright (c) 2024, zhao.shaowei <nsearchf@yeah.net>
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.


/* Automatically generated by parse_opcodes */
const MATCH_FCVT_L_S: u32 = 0xc0200053;
const MASK_FCVT_L_S: u32 = 0xfff0007f;
const MATCH_FCVT_LU_S: u32 = 0xc0300053;
const MASK_FCVT_LU_S: u32 = 0xfff0007f;
const MATCH_FCVT_S_L: u32 = 0xd0200053;
const MASK_FCVT_S_L: u32 = 0xfff0007f;
const MATCH_FCVT_S_LU: u32 = 0xd0300053;
const MASK_FCVT_S_LU: u32 = 0xfff0007f;
