// Copyright (c) 2024, zhao.shaowei <nsearchf@yeah.net>
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.


/* Automatically generated by parse_opcodes */
const MATCH_SLLI: u32 = 0x1013;
const MASK_SLLI: u32 = 0xfe00707f;
const MATCH_SRAI: u32 = 0x40005013;
const MASK_SRAI: u32 = 0xfe00707f;
const MATCH_SRLI: u32 = 0x5013;
const MASK_SRLI: u32 = 0xfe00707f;
