// Copyright (c) 2024, zhao.shaowei <nsearchf@yeah.net>
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.


/* Automatically generated by parse_opcodes */
const MATCH_AMOADD_D: u32 = 0x302f;
const MASK_AMOADD_D: u32 = 0xf800707f;
const MATCH_AMOAND_D: u32 = 0x6000302f;
const MASK_AMOAND_D: u32 = 0xf800707f;
const MATCH_AMOMAX_D: u32 = 0xa000302f;
const MASK_AMOMAX_D: u32 = 0xf800707f;
const MATCH_AMOMAXU_D: u32 = 0xe000302f;
const MASK_AMOMAXU_D: u32 = 0xf800707f;
const MATCH_AMOMIN_D: u32 = 0x8000302f;
const MASK_AMOMIN_D: u32 = 0xf800707f;
const MATCH_AMOMINU_D: u32 = 0xc000302f;
const MASK_AMOMINU_D: u32 = 0xf800707f;
const MATCH_AMOOR_D: u32 = 0x4000302f;
const MASK_AMOOR_D: u32 = 0xf800707f;
const MATCH_AMOSWAP_D: u32 = 0x800302f;
const MASK_AMOSWAP_D: u32 = 0xf800707f;
const MATCH_AMOXOR_D: u32 = 0x2000302f;
const MASK_AMOXOR_D: u32 = 0xf800707f;
const MATCH_LR_D: u32 = 0x1000302f;
const MASK_LR_D: u32 = 0xf9f0707f;
const MATCH_SC_D: u32 = 0x1800302f;
const MASK_SC_D: u32 = 0xf800707f;
