// Copyright (c) 2024, zhao.shaowei <nsearchf@yeah.net>
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.


/* Automatically generated by parse_opcodes */
const MATCH_FADD_D: u32 = 0x2000053;
const MASK_FADD_D: u32 = 0xfe00007f;
const MATCH_FCLASS_D: u32 = 0xe2001053;
const MASK_FCLASS_D: u32 = 0xfff0707f;
const MATCH_FCVT_D_S: u32 = 0x42000053;
const MASK_FCVT_D_S: u32 = 0xfff0007f;
const MATCH_FCVT_D_W: u32 = 0xd2000053;
const MASK_FCVT_D_W: u32 = 0xfff0007f;
const MATCH_FCVT_D_WU: u32 = 0xd2100053;
const MASK_FCVT_D_WU: u32 = 0xfff0007f;
const MATCH_FCVT_S_D: u32 = 0x40100053;
const MASK_FCVT_S_D: u32 = 0xfff0007f;
const MATCH_FCVT_W_D: u32 = 0xc2000053;
const MASK_FCVT_W_D: u32 = 0xfff0007f;
const MATCH_FCVT_WU_D: u32 = 0xc2100053;
const MASK_FCVT_WU_D: u32 = 0xfff0007f;
const MATCH_FDIV_D: u32 = 0x1a000053;
const MASK_FDIV_D: u32 = 0xfe00007f;
const MATCH_FEQ_D: u32 = 0xa2002053;
const MASK_FEQ_D: u32 = 0xfe00707f;
const MATCH_FLD: u32 = 0x3007;
const MASK_FLD: u32 = 0x707f;
const MATCH_FLE_D: u32 = 0xa2000053;
const MASK_FLE_D: u32 = 0xfe00707f;
const MATCH_FLT_D: u32 = 0xa2001053;
const MASK_FLT_D: u32 = 0xfe00707f;
const MATCH_FMADD_D: u32 = 0x2000043;
const MASK_FMADD_D: u32 = 0x600007f;
const MATCH_FMAX_D: u32 = 0x2a001053;
const MASK_FMAX_D: u32 = 0xfe00707f;
const MATCH_FMIN_D: u32 = 0x2a000053;
const MASK_FMIN_D: u32 = 0xfe00707f;
const MATCH_FMSUB_D: u32 = 0x2000047;
const MASK_FMSUB_D: u32 = 0x600007f;
const MATCH_FMUL_D: u32 = 0x12000053;
const MASK_FMUL_D: u32 = 0xfe00007f;
const MATCH_FNMADD_D: u32 = 0x200004f;
const MASK_FNMADD_D: u32 = 0x600007f;
const MATCH_FNMSUB_D: u32 = 0x200004b;
const MASK_FNMSUB_D: u32 = 0x600007f;
const MATCH_FSD: u32 = 0x3027;
const MASK_FSD: u32 = 0x707f;
const MATCH_FSGNJ_D: u32 = 0x22000053;
const MASK_FSGNJ_D: u32 = 0xfe00707f;
const MATCH_FSGNJN_D: u32 = 0x22001053;
const MASK_FSGNJN_D: u32 = 0xfe00707f;
const MATCH_FSGNJX_D: u32 = 0x22002053;
const MASK_FSGNJX_D: u32 = 0xfe00707f;
const MATCH_FSQRT_D: u32 = 0x5a000053;
const MASK_FSQRT_D: u32 = 0xfff0007f;
const MATCH_FSUB_D: u32 = 0xa000053;
const MASK_FSUB_D: u32 = 0xfe00007f;
