// Copyright (c) 2024, zhao.shaowei <nsearchf@yeah.net>
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.


/* Automatically generated by parse_opcodes */
const MATCH_C_ADDIW: u32 = 0x2001;
const MASK_C_ADDIW: u32 = 0xe003;
const MATCH_C_ADDW: u32 = 0x9c21;
const MASK_C_ADDW: u32 = 0xfc63;
const MATCH_C_LD: u32 = 0x6000;
const MASK_C_LD: u32 = 0xe003;
const MATCH_C_LDSP: u32 = 0x6002;
const MASK_C_LDSP: u32 = 0xe003;
const MATCH_C_SD: u32 = 0xe000;
const MASK_C_SD: u32 = 0xe003;
const MATCH_C_SDSP: u32 = 0xe002;
const MASK_C_SDSP: u32 = 0xe003;
const MATCH_C_SLLI: u32 = 0x2;
const MASK_C_SLLI: u32 = 0xe003;
const MATCH_C_SRAI: u32 = 0x8401;
const MASK_C_SRAI: u32 = 0xec03;
const MATCH_C_SRLI: u32 = 0x8001;
const MASK_C_SRLI: u32 = 0xec03;
const MATCH_C_SUBW: u32 = 0x9c01;
const MASK_C_SUBW: u32 = 0xfc63;
