// Copyright (c) 2024, zhao.shaowei <nsearchf@yeah.net>
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.


/* Automatically generated by parse_opcodes */
const MATCH_ADDIW: u32 = 0x1b;
const MASK_ADDIW: u32 = 0x707f;
const MATCH_ADDW: u32 = 0x3b;
const MASK_ADDW: u32 = 0xfe00707f;
const MATCH_LD: u32 = 0x3003;
const MASK_LD: u32 = 0x707f;
const MATCH_LWU: u32 = 0x6003;
const MASK_LWU: u32 = 0x707f;
const MATCH_SD: u32 = 0x3023;
const MASK_SD: u32 = 0x707f;
const MATCH_SLLI: u32 = 0x1013;
const MASK_SLLI: u32 = 0xfc00707f;
const MATCH_SLLIW: u32 = 0x101b;
const MASK_SLLIW: u32 = 0xfe00707f;
const MATCH_SLLW: u32 = 0x103b;
const MASK_SLLW: u32 = 0xfe00707f;
const MATCH_SRAI: u32 = 0x40005013;
const MASK_SRAI: u32 = 0xfc00707f;
const MATCH_SRAIW: u32 = 0x4000501b;
const MASK_SRAIW: u32 = 0xfe00707f;
const MATCH_SRAW: u32 = 0x4000503b;
const MASK_SRAW: u32 = 0xfe00707f;
const MATCH_SRLI: u32 = 0x5013;
const MASK_SRLI: u32 = 0xfc00707f;
const MATCH_SRLIW: u32 = 0x501b;
const MASK_SRLIW: u32 = 0xfe00707f;
const MATCH_SRLW: u32 = 0x503b;
const MASK_SRLW: u32 = 0xfe00707f;
const MATCH_SUBW: u32 = 0x4000003b;
const MASK_SUBW: u32 = 0xfe00707f;
